import { oxfordQuestions as oldQuestions } from './src/data/oxford';

// The new questions from the user request
const newQuestions = [
  {
    id: 'oxford-ch1-q1',
    globalId: 1,
    source: 'oxford',
    chapter: 'Chapter 1',
    chapterNum: 1,
    chapterTitle: 'Introduction to Geology',
    text: `Which of the following statements regarding the scientific methods is true?`,
    choices: {
      a: `A hypothesis must be agreed upon by more than one scientist`,
      b: `A theory is a hypothesis that has withstood many scientific tests`,
      c: `A theory is proven to be true, and therefore may not be discarded`,
      d: `A hypothesis cannot predict the outcome of scientific experiments`,
    },
    correctAnswer: 'b',
    imageUrl: null,
    category: 'Introduction to Geology',
    tags: ['Introduction to Geology', 'Oxford'],
    difficulty: 'medium',
  },
  {
    id: 'oxford-ch1-q2',
    globalId: 2,
    source: 'oxford',
    chapter: 'Chapter 1',
    chapterNum: 1,
    chapterTitle: 'Introduction to Geology',
    text: `According to the principle of uniformatarianism,`,
    choices: {
      a: `geologic processes we observe today have operated in the past`,
      b: `geologic process in the past operated at the same rate as they do today`,
      c: `all of the planets formed from a uniform solar nebula`,
      d: `early Earth was covered by a uniform magma ocean`,
    },
    correctAnswer: 'a',
    imageUrl: null,
    category: 'Introduction to Geology',
    tags: ['Introduction to Geology', 'Oxford'],
    difficulty: 'medium',
  },
  {
    id: 'oxford-ch1-q3',
    globalId: 3,
    source: 'oxford',
    chapter: 'Chapter 1',
    chapterNum: 1,
    chapterTitle: 'Introduction to Geology',
    text: `Approximately how long ago did the Big Bang take place?`,
    choices: {
      a: `10-15 thousand years ago`,
      b: `10-15 million years ago`,
      c: `100-150 million years ago`,
      d: `10-15 billion years ago`,
    },
    correctAnswer: 'd',
    imageUrl: null,
    category: 'Introduction to Geology',
    tags: ['Introduction to Geology', 'Oxford'],
    difficulty: 'medium',
  },
  {
    id: 'oxford-ch1-q4',
    globalId: 4,
    source: 'oxford',
    chapter: 'Chapter 1',
    chapterNum: 1,
    chapterTitle: 'Introduction to Geology',
    text: `Under intense pressure and high temperature, hydrogen atoms combine to form helium. This process is called:`,
    choices: {
      a: `nuclear fusion`,
      b: `nuclear fission`,
      c: `metamorphism`,
      d: `convection`,
    },
    correctAnswer: 'a',
    imageUrl: null,
    category: 'Introduction to Geology',
    tags: ['Introduction to Geology', 'Oxford'],
    difficulty: 'medium',
  },
  {
    id: 'oxford-ch1-q5',
    globalId: 5,
    source: 'oxford',
    chapter: 'Chapter 1',
    chapterNum: 1,
    chapterTitle: 'Introduction to Geology',
    text: `What are the two most abundant elements in nebula (gas clouds) in the universe?`,
    choices: {
      a: `nitrogen and oxygen`,
      b: `oxygen and silicon`,
      c: `hydrogen and helium`,
      d: `iron and nickel`,
    },
    correctAnswer: 'c',
    imageUrl: null,
    category: 'Introduction to Geology',
    tags: ['Introduction to Geology', 'Oxford'],
    difficulty: 'medium',
  },
  {
    id: 'oxford-ch1-q6',
    globalId: 6,
    source: 'oxford',
    chapter: 'Chapter 1',
    chapterNum: 1,
    chapterTitle: 'Introduction to Geology',
    text: `The process by which an originally homogeneous Earth developed a dense core and a light crust is called:`,
    choices: {
      a: `metamorphism`,
      b: `differentiation`,
      c: `accretion`,
      d: `compression`,
    },
    correctAnswer: 'b',
    imageUrl: null,
    category: 'Introduction to Geology',
    tags: ['Introduction to Geology', 'Oxford'],
    difficulty: 'medium',
  },
  {
    id: 'oxford-ch1-q7',
    globalId: 7,
    source: 'oxford',
    chapter: 'Chapter 1',
    chapterNum: 1,
    chapterTitle: 'Introduction to Geology',
    text: `The heat that caused melting in the Earth's early history was supplied from which of the following events or causes?`,
    choices: {
      a: `volcanic activity and radioactivity`,
      b: `solar heating and volcanic activity`,
      c: `a large impact event and radioactivity`,
      d: `a large impact event and solar heating`,
    },
    correctAnswer: 'c',
    imageUrl: null,
    category: 'Introduction to Geology',
    tags: ['Introduction to Geology', 'Oxford'],
    difficulty: 'medium',
  },
  {
    id: 'oxford-ch1-q8',
    globalId: 8,
    source: 'oxford',
    chapter: 'Chapter 1',
    chapterNum: 1,
    chapterTitle: 'Introduction to Geology',
    text: `How thick is the crust of the Earth?`,
    choices: {
      a: `about 4 miles`,
      b: `about 4 km`,
      c: `about 40 km`,
      d: `about 400 km`,
    },
    correctAnswer: 'c',
    imageUrl: null,
    category: 'Introduction to Geology',
    tags: ['Introduction to Geology', 'Oxford'],
    difficulty: 'medium',
  },
  {
    id: 'oxford-ch1-q9',
    globalId: 9,
    source: 'oxford',
    chapter: 'Chapter 1',
    chapterNum: 1,
    chapterTitle: 'Introduction to Geology',
    text: `The layer that separates crust from core is the?`,
    choices: {
      a: `magma layer`,
      b: `lithosphere`,
      c: `mantle`,
      d: `continent`,
    },
    correctAnswer: 'c',
    imageUrl: null,
    category: 'Introduction to Geology',
    tags: ['Introduction to Geology', 'Oxford'],
    difficulty: 'medium',
  },
  {
    id: 'oxford-ch1-q10',
    globalId: 10,
    source: 'oxford',
    chapter: 'Chapter 1',
    chapterNum: 1,
    chapterTitle: 'Introduction to Geology',
    text: `What drives the Earth's internal heat engine?`,
    choices: {
      a: `radioactivity`,
      b: `solar energy`,
      c: `volcanoes`,
      d: `ocean tides`,
    },
    correctAnswer: 'a',
    imageUrl: null,
    category: 'Introduction to Geology',
    tags: ['Introduction to Geology', 'Oxford'],
    difficulty: 'medium',
  },
  {
    id: 'oxford-ch1-q11',
    globalId: 11,
    source: 'oxford',
    chapter: 'Chapter 1',
    chapterNum: 1,
    chapterTitle: 'Introduction to Geology',
    text: `In general, igneous rocks:`,
    choices: {
      a: `form at relatively high temperatures`,
      b: `form by crystallization of solids from a liquid`,
      c: `form at high and low pressures`,
      d: `all of the above`,
    },
    correctAnswer: 'd',
    imageUrl: null,
    category: 'Introduction to Geology',
    tags: ['Introduction to Geology', 'Oxford'],
    difficulty: 'medium',
  },
  {
    id: 'oxford-ch1-q12',
    globalId: 12,
    source: 'oxford',
    chapter: 'Chapter 1',
    chapterNum: 1,
    chapterTitle: 'Introduction to Geology',
    text: `Minerals:`,
    choices: {
      a: `can form by life-processes -- organic`,
      b: `are crystalline solids`,
      c: `have a unique chemical composition`,
      d: `can be any state (solid, liquid, or gas) as long as that state occurs naturally`,
    },
    correctAnswer: 'b',
    imageUrl: null,
    category: 'Introduction to Geology',
    tags: ['Introduction to Geology', 'Oxford'],
    difficulty: 'medium',
  },
  {
    id: 'oxford-ch1-q13',
    globalId: 13,
    source: 'oxford',
    chapter: 'Chapter 1',
    chapterNum: 1,
    chapterTitle: 'Introduction to Geology',
    text: `Metamorphic rocks are changed rocks. Which of the following rock types could be the "parent" of a metamorphic rock?`,
    choices: {
      a: `sedimentary`,
      b: `igneous`,
      c: `metamorphic`,
      d: `all of the above`,
    },
    correctAnswer: 'd',
    imageUrl: null,
    category: 'Introduction to Geology',
    tags: ['Introduction to Geology', 'Oxford'],
    difficulty: 'medium',
  },
  {
    id: 'oxford-ch1-q14',
    globalId: 14,
    source: 'oxford',
    chapter: 'Chapter 1',
    chapterNum: 1,
    chapterTitle: 'Introduction to Geology',
    text: `_______involves transfer of heat by the physical movement of the material:`,
    choices: {
      a: `conduction`,
      b: `convection`,
      c: `metamorphism`,
      d: `radiation`,
    },
    correctAnswer: 'b',
    imageUrl: null,
    category: 'Introduction to Geology',
    tags: ['Introduction to Geology', 'Oxford'],
    difficulty: 'medium',
  },
  {
    id: 'oxford-ch1-q15',
    globalId: 15,
    source: 'oxford',
    chapter: 'Chapter 1',
    chapterNum: 1,
    chapterTitle: 'Introduction to Geology',
    text: `__________is called the "father" of geology.`,
    choices: {
      a: `John Butler`,
      b: `Art Smith`,
      c: `James Hutton`,
      d: `Alfred Wegner`,
    },
    correctAnswer: 'c',
    imageUrl: null,
    category: 'Introduction to Geology',
    tags: ['Introduction to Geology', 'Oxford'],
    difficulty: 'medium',
  },
  {
    id: 'oxford-ch1-q16',
    globalId: 16,
    source: 'oxford',
    chapter: 'Chapter 1',
    chapterNum: 1,
    chapterTitle: 'Introduction to Geology',
    text: `New seafloor is created at a ____________?`,
    choices: {
      a: `deep-sea trench`,
      b: `mid-ocean ridge`,
      c: `subduction zone`,
      d: `transform fault`,
    },
    correctAnswer: 'b',
    imageUrl: null,
    category: 'Introduction to Geology',
    tags: ['Introduction to Geology', 'Oxford'],
    difficulty: 'medium',
  },
  {
    id: 'oxford-ch1-q17',
    globalId: 17,
    source: 'oxford',
    chapter: 'Chapter 1',
    chapterNum: 1,
    chapterTitle: 'Introduction to Geology',
    text: `The descent of oceanic lithosphere into the mantle is the process of _______?`,
    choices: {
      a: `accretion`,
      b: `subduction`,
      c: `divergence zone`,
      d: `contraction fault`,
    },
    correctAnswer: 'b',
    imageUrl: null,
    category: 'Introduction to Geology',
    tags: ['Introduction to Geology', 'Oxford'],
    difficulty: 'medium',
  },
  {
    id: 'oxford-ch1-q18',
    globalId: 18,
    source: 'oxford',
    chapter: 'Chapter 1',
    chapterNum: 1,
    chapterTitle: 'Introduction to Geology',
    text: `Which of the following features is not associated with a convergent plate boundary?`,
    choices: {
      a: `a mid-ocean ridge`,
      b: `earthquakes`,
      c: `a deep-sea trench zone`,
      d: `volcanic activity`,
    },
    correctAnswer: 'a',
    imageUrl: null,
    category: 'Introduction to Geology',
    tags: ['Introduction to Geology', 'Oxford'],
    difficulty: 'medium',
  },
  {
    id: 'oxford-ch1-q19',
    globalId: 19,
    source: 'oxford',
    chapter: 'Chapter 1',
    chapterNum: 1,
    chapterTitle: 'Introduction to Geology',
    text: `The greatest threat to our environment is ___________?`,
    choices: {
      a: `volcanoes`,
      b: `earthquakes`,
      c: `humans`,
      d: `bacteria`,
    },
    correctAnswer: 'c',
    imageUrl: null,
    category: 'Introduction to Geology',
    tags: ['Introduction to Geology', 'Oxford'],
    difficulty: 'medium',
  },
  {
    id: 'oxford-ch1-q20',
    globalId: 20,
    source: 'oxford',
    chapter: 'Chapter 1',
    chapterNum: 1,
    chapterTitle: 'Introduction to Geology',
    text: `Earth materials always trace the complete rock cycle from sediment through igneous rocks.`,
    choices: {
      a: `True`,
      b: `False`,
      c: ``,
      d: ``,
    },
    correctAnswer: 'b',
    imageUrl: null,
    category: 'Introduction to Geology',
    tags: ['Introduction to Geology', 'Oxford'],
    difficulty: 'medium',
  },
  {
    id: 'oxford-ch1-q21',
    globalId: 21,
    source: 'oxford',
    chapter: 'Chapter 1',
    chapterNum: 1,
    chapterTitle: 'Introduction to Geology',
    text: `The terms crust and lithosphere are synonymous.`,
    choices: {
      a: `True`,
      b: `False`,
      c: ``,
      d: ``,
    },
    correctAnswer: 'b',
    imageUrl: null,
    category: 'Introduction to Geology',
    tags: ['Introduction to Geology', 'Oxford'],
    difficulty: 'medium',
  },
  {
    id: 'oxford-ch1-q22',
    globalId: 22,
    source: 'oxford',
    chapter: 'Chapter 1',
    chapterNum: 1,
    chapterTitle: 'Introduction to Geology',
    text: `The terms mantle and asthenosphere are synonymous.`,
    choices: {
      a: `True`,
      b: `False`,
      c: ``,
      d: ``,
    },
    correctAnswer: 'b',
    imageUrl: null,
    category: 'Introduction to Geology',
    tags: ['Introduction to Geology', 'Oxford'],
    difficulty: 'medium',
  },
  {
    id: 'oxford-ch1-q23',
    globalId: 23,
    source: 'oxford',
    chapter: 'Chapter 1',
    chapterNum: 1,
    chapterTitle: 'Introduction to Geology',
    text: `Because we rarely witness dramatic changes in the Earth, we can conclude that the Earth is not changing very much.`,
    choices: {
      a: `True`,
      b: `False`,
      c: ``,
      d: ``,
    },
    correctAnswer: 'b',
    imageUrl: null,
    category: 'Introduction to Geology',
    tags: ['Introduction to Geology', 'Oxford'],
    difficulty: 'medium',
  },
  {
    id: 'oxford-ch1-q24',
    globalId: 24,
    source: 'oxford',
    chapter: 'Chapter 1',
    chapterNum: 1,
    chapterTitle: 'Introduction to Geology',
    text: `The motions of the three types of plate boundaries would be described as divergent, convergent, and static.`,
    choices: {
      a: `True`,
      b: `False`,
      c: ``,
      d: ``,
    },
    correctAnswer: 'b',
    imageUrl: null,
    category: 'Introduction to Geology',
    tags: ['Introduction to Geology', 'Oxford'],
    difficulty: 'medium',
  },
  {
    id: 'oxford-ch1-q25',
    globalId: 25,
    source: 'oxford',
    chapter: 'Chapter 1',
    chapterNum: 1,
    chapterTitle: 'Introduction to Geology',
    text: `The crust of the Earth is static and stable.`,
    choices: {
      a: `True`,
      b: `False`,
      c: ``,
      d: ``,
    },
    correctAnswer: 'b',
    imageUrl: null,
    category: 'Introduction to Geology',
    tags: ['Introduction to Geology', 'Oxford'],
    difficulty: 'medium',
  },
  {
    id: 'oxford-ch1-q26',
    globalId: 26,
    source: 'oxford',
    chapter: 'Chapter 1',
    chapterNum: 1,
    chapterTitle: 'Introduction to Geology',
    text: `Features useful in defining plate boundaries include all except:`,
    choices: {
      a: `shorelines between continents and oceans`,
      b: `distribution of volcanoes`,
      c: `distribution of earthquakes`,
      d: `distribution of mountain ranges`,
    },
    correctAnswer: 'a',
    imageUrl: null,
    category: 'Introduction to Geology',
    tags: ['Introduction to Geology', 'Oxford'],
    difficulty: 'medium',
  },
  {
    id: 'oxford-ch1-q27',
    globalId: 27,
    source: 'oxford',
    chapter: 'Chapter 1',
    chapterNum: 1,
    chapterTitle: 'Introduction to Geology',
    text: `The age of the Earth is currently thought to be`,
    choices: {
      a: `about 6,000 years old`,
      b: `about 6 billion years old`,
      c: `about 4,500,000 years old`,
      d: `about 4,500,000,000 years old`,
    },
    correctAnswer: 'd',
    imageUrl: null,
    category: 'Introduction to Geology',
    tags: ['Introduction to Geology', 'Oxford'],
    difficulty: 'medium',
  },
  {
    id: 'oxford-ch1-q28',
    globalId: 28,
    source: 'oxford',
    chapter: 'Chapter 1',
    chapterNum: 1,
    chapterTitle: 'Introduction to Geology',
    text: `The contribution made to geology by James Hutton was:`,
    choices: {
      a: `the recognition that processes still active today could produce almost any known rock type.`,
      b: `the description of plausible processes for converting one rock type to another.`,
      c: `a change in outlook on Earth processes from a catastrophic to a uniformitarian one.`,
      d: `all of the above`,
    },
    correctAnswer: 'd',
    imageUrl: null,
    category: 'Introduction to Geology',
    tags: ['Introduction to Geology', 'Oxford'],
    difficulty: 'medium',
  },
  {
    id: 'oxford-ch1-q29',
    globalId: 29,
    source: 'oxford',
    chapter: 'Chapter 1',
    chapterNum: 1,
    chapterTitle: 'Introduction to Geology',
    text: `One of geology's greatest contributions to human thought is:`,
    choices: {
      a: `the realization that the world is round`,
      b: `the realization that the sun not the Earth is the center of the solar system`,
      c: `the recognition of the long span of time involved in Earth history`,
      d: `the recognition that the Earth is the center of the solar system`,
    },
    correctAnswer: 'c',
    imageUrl: null,
    category: 'Introduction to Geology',
    tags: ['Introduction to Geology', 'Oxford'],
    difficulty: 'medium',
  },
  {
    id: 'oxford-ch1-q30',
    globalId: 30,
    source: 'oxford',
    chapter: 'Chapter 1',
    chapterNum: 1,
    chapterTitle: 'Introduction to Geology',
    text: `Evidence of uniformitarian change includes:`,
    choices: {
      a: `glacial deposits in areas where no glaciers are presently found.`,
      b: `fossils of marine animals found at high elevation`,
      c: `continents covered by sediments deposited in an ocean`,
      d: `wide canyons cut by small streams`,
    },
    correctAnswer: 'e',
    imageUrl: null,
    category: 'Introduction to Geology',
    tags: ['Introduction to Geology', 'Oxford'],
    difficulty: 'medium',
  },
  {
    id: 'oxford-ch1-q31',
    globalId: 31,
    source: 'oxford',
    chapter: 'Chapter 1',
    chapterNum: 1,
    chapterTitle: 'Introduction to Geology',
    text: `Living organisms have been on Earth for ______ of Earth's history?`,
    choices: {
      a: `less than 1%`,
      b: `about 20%`,
      c: `about 50%`,
      d: `about 80%`,
    },
    correctAnswer: 'd',
    imageUrl: null,
    category: 'Introduction to Geology',
    tags: ['Introduction to Geology', 'Oxford'],
    difficulty: 'medium',
  },
  {
    id: 'oxford-ch1-q32',
    globalId: 32,
    source: 'oxford',
    chapter: 'Chapter 1',
    chapterNum: 1,
    chapterTitle: 'Introduction to Geology',
    text: `Humans have been on Earth for _________ of Earth;s history?`,
    choices: {
      a: `less than 1%`,
      b: `about 20%`,
      c: `about 50%`,
      d: `about 80%`,
    },
    correctAnswer: 'a',
    imageUrl: null,
    category: 'Introduction to Geology',
    tags: ['Introduction to Geology', 'Oxford'],
    difficulty: 'medium',
  },
  {
    id: 'oxford-ch1-q33',
    globalId: 33,
    source: 'oxford',
    chapter: 'Chapter 1',
    chapterNum: 1,
    chapterTitle: 'Introduction to Geology',
    text: `What caused dust and condensing material to accrete into planetesimals?`,
    choices: {
      a: `heating of gases`,
      b: `gravitational attraction and collisions`,
      c: `nuclear fusion`,
      d: `rotation of the proto-sun`,
    },
    correctAnswer: 'b',
    imageUrl: null,
    category: 'Introduction to Geology',
    tags: ['Introduction to Geology', 'Oxford'],
    difficulty: 'medium',
  },
  {
    id: 'oxford-ch1-q34',
    globalId: 34,
    source: 'oxford',
    chapter: 'Chapter 1',
    chapterNum: 1,
    chapterTitle: 'Introduction to Geology',
    text: `Which of the following is not one of the four inner planets?`,
    choices: {
      a: `Mars`,
      b: `Earth`,
      c: `Neptune`,
      d: `Mars`,
    },
    correctAnswer: 'c',
    imageUrl: null,
    category: 'Introduction to Geology',
    tags: ['Introduction to Geology', 'Oxford'],
    difficulty: 'medium',
  },
  {
    id: 'oxford-ch1-q35',
    globalId: 35,
    source: 'oxford',
    chapter: 'Chapter 1',
    chapterNum: 1,
    chapterTitle: 'Introduction to Geology',
    text: `The outer planets are composed mostly of ?`,
    choices: {
      a: `rocks and ice`,
      b: `oxygen and nitrogen`,
      c: `hydrogen and helium`,
      d: `helium and krypton`,
    },
    correctAnswer: 'c',
    imageUrl: null,
    category: 'Introduction to Geology',
    tags: ['Introduction to Geology', 'Oxford'],
    difficulty: 'medium',
  },
  {
    id: 'oxford-ch1-q36',
    globalId: 36,
    source: 'oxford',
    chapter: 'Chapter 1',
    chapterNum: 1,
    chapterTitle: 'Introduction to Geology',
    text: `The moon is ?`,
    choices: {
      a: `older than the sun`,
      b: `older than most meteorites`,
      c: `older than the Earth`,
      d: `none of these`,
    },
    correctAnswer: 'd',
    imageUrl: null,
    category: 'Introduction to Geology',
    tags: ['Introduction to Geology', 'Oxford'],
    difficulty: 'medium',
  },
  {
    id: 'oxford-ch1-q37',
    globalId: 37,
    source: 'oxford',
    chapter: 'Chapter 1',
    chapterNum: 1,
    chapterTitle: 'Introduction to Geology',
    text: `The name of the layer of the Earth that separates the crust from the core is the ___?`,
    choices: {
      a: `magma`,
      b: `lithosphere`,
      c: `asthenosphere`,
      d: `mantle`,
    },
    correctAnswer: 'd',
    imageUrl: null,
    category: 'Introduction to Geology',
    tags: ['Introduction to Geology', 'Oxford'],
    difficulty: 'medium',
  },
  {
    id: 'oxford-ch1-q38',
    globalId: 38,
    source: 'oxford',
    chapter: 'Chapter 1',
    chapterNum: 1,
    chapterTitle: 'Introduction to Geology',
    text: `What powers the Earth's internal heat engine?`,
    choices: {
      a: `radioactivity`,
      b: `solar energy`,
      c: `volcanoes`,
      d: `ocean tides`,
    },
    correctAnswer: 'a',
    imageUrl: null,
    category: 'Introduction to Geology',
    tags: ['Introduction to Geology', 'Oxford'],
    difficulty: 'medium',
  },
  {
    id: 'oxford-ch1-q39',
    globalId: 39,
    source: 'oxford',
    chapter: 'Chapter 1',
    chapterNum: 1,
    chapterTitle: 'Introduction to Geology',
    text: `The Earth's external heat engine is not responsible for which of the following:`,
    choices: {
      a: `climate`,
      b: `erosion`,
      c: `tides`,
      d: `winds`,
    },
    correctAnswer: 'c',
    imageUrl: null,
    category: 'Introduction to Geology',
    tags: ['Introduction to Geology', 'Oxford'],
    difficulty: 'medium',
  },
  {
    id: 'oxford-ch1-q40',
    globalId: 40,
    source: 'oxford',
    chapter: 'Chapter 1',
    chapterNum: 1,
    chapterTitle: 'Introduction to Geology',
    text: `Oxygen built up in the Earth's atmosphere because:`,
    choices: {
      a: `the oceans separated from the crust`,
      b: `rocks weathered and released their oxygen`,
      c: `algae and other organisms employed photosynthesis`,
      d: `oxygen settled on Earth from planets further from the sun`,
    },
    correctAnswer: 'c',
    imageUrl: null,
    category: 'Introduction to Geology',
    tags: ['Introduction to Geology', 'Oxford'],
    difficulty: 'medium',
  },
  {
    id: 'oxford-ch1-q41',
    globalId: 41,
    source: 'oxford',
    chapter: 'Chapter 1',
    chapterNum: 1,
    chapterTitle: 'Introduction to Geology',
    text: `Which of the planets is not geologically active?`,
    choices: {
      a: `Mars`,
      b: `Mercury`,
      c: `Venus`,
      d: `Earth`,
    },
    correctAnswer: 'b',
    imageUrl: null,
    category: 'Introduction to Geology',
    tags: ['Introduction to Geology', 'Oxford'],
    difficulty: 'medium',
  },
  {
    id: 'oxford-ch1-q42',
    globalId: 42,
    source: 'oxford',
    chapter: 'Chapter 1',
    chapterNum: 1,
    chapterTitle: 'Introduction to Geology',
    text: `When did geologists develop the theory of plate tectonics`,
    choices: {
      a: `in the mid 1800s`,
      b: `in the early 1900s`,
      c: `in the 1950s`,
      d: `in the 1960s`,
    },
    correctAnswer: 'd',
    imageUrl: null,
    category: 'Introduction to Geology',
    tags: ['Introduction to Geology', 'Oxford'],
    difficulty: 'medium',
  },
  {
    id: 'oxford-ch1-q43',
    globalId: 43,
    source: 'oxford',
    chapter: 'Chapter 1',
    chapterNum: 1,
    chapterTitle: 'Introduction to Geology',
    text: `The lithosphere is approximately ______ kilometers thick.`,
    choices: {
      a: `1-2`,
      b: `5-10`,
      c: `50-100`,
      d: `100-200`,
    },
    correctAnswer: 'c',
    imageUrl: null,
    category: 'Introduction to Geology',
    tags: ['Introduction to Geology', 'Oxford'],
    difficulty: 'medium',
  },
  {
    id: 'oxford-ch1-q44',
    globalId: 44,
    source: 'oxford',
    chapter: 'Chapter 1',
    chapterNum: 1,
    chapterTitle: 'Introduction to Geology',
    text: `The asthenosphere is _________.`,
    choices: {
      a: `cool and strong`,
      b: `cool and weak`,
      c: `hot and strong`,
      d: `hot and weak`,
    },
    correctAnswer: 'd',
    imageUrl: null,
    category: 'Introduction to Geology',
    tags: ['Introduction to Geology', 'Oxford'],
    difficulty: 'medium',
  },
  {
    id: 'oxford-ch1-q45',
    globalId: 45,
    source: 'oxford',
    chapter: 'Chapter 1',
    chapterNum: 1,
    chapterTitle: 'Introduction to Geology',
    text: `The Earth's lithosphere is broken into approximately ______ large, rigid plates.`,
    choices: {
      a: `2`,
      b: `12`,
      c: `50`,
      d: `100`,
    },
    correctAnswer: 'b',
    imageUrl: null,
    category: 'Introduction to Geology',
    tags: ['Introduction to Geology', 'Oxford'],
    difficulty: 'medium',
  },
  {
    id: 'oxford-ch1-q46',
    globalId: 46,
    source: 'oxford',
    chapter: 'Chapter 1',
    chapterNum: 1,
    chapterTitle: 'Introduction to Geology',
    text: `A __________ plate boundary is illustrated in the figure show above.`,
    choices: {
      a: `transform fault`,
      b: `divergent`,
      c: `convergent - subduction`,
      d: `convergent - continent/continent collision`,
    },
    correctAnswer: 'b',
    imageUrl: 'https://uh.edu/~jbutler/physical/chap1fig1.gif',
    category: 'Introduction to Geology',
    tags: ['Introduction to Geology', 'Oxford'],
    difficulty: 'medium',
  }
];

// Let's see if we find any of the old image-bearing questions in this array or if we can match them
const match = (text: string) => {
  return newQuestions.find(q => q.text.toLowerCase().includes(text.toLowerCase()));
};

console.log('Match 1 (hotspot volcanoes):', match('hotspot volcanoes'));
console.log('Match 2 (subduction):', match('subduction'));
console.log('Match 3 (pyroxene):', match('pyroxene'));
